# Generated by Django 2.2.20 on 2021-04-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_receiver_woocommerce', '0004_rename_id_to_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='woocommerceorder',
            name='action',
            field=models.CharField(choices=[('enroll', 'enroll'), ('unenroll', 'unenroll')], default='enroll', max_length=8),
            preserve_default=False,
        ),
    ]
