# Generated by Django 2.2.20 on 2021-04-14 02:46

from django.db import migrations, models
import django.db.models.deletion


def populate(apps, schema_editor):
   model = apps.get_model('webhook_receiver_shopify', 'shopifyorder')
   for index, item in enumerate(model.objects.all(), start=1):
       item.id = index
       item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_receiver_shopify', '0006_add_webhook_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopifyorder',
            old_name='id',
            new_name='order_id',
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.RunPython(populate),
        migrations.AlterField(
            model_name='shopifyorder',
            name='order_id',
            field=models.BigIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='shopifyorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webhook_receiver_shopify.ShopifyOrder'),
        ),
    ]
