# Generated by Django 2.2.20 on 2021-04-14 02:46

from django.db import migrations, models
from django.db.migrations.operations.fields import RemoveField
from django.db.migrations.operations.special import RunSQL
import django.db.models.deletion


def populate(apps, schema_editor):
   model = apps.get_model('webhook_receiver_shopify', 'shopifyorder')
   for index, item in enumerate(model.objects.all(), start=1):
       item.id = index
       item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_receiver_shopify', '0007_fix_unique_constraint_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webhook_receiver_shopify.ShopifyOrder', db_constraint=False, db_index=True, null=False),
        ),
        migrations.RenameField(
            model_name='shopifyorder',
            old_name='id',
            new_name='order_id',
        ),
        migrations.AlterField(
            model_name='shopifyorder',
            name='order_id',
            field=models.BigIntegerField(editable=False),
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RunPython(populate),
        migrations.AlterField(
            model_name='shopifyorderitem',
            name='order',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='webhook_receiver_shopify.ShopifyOrder'
            ),
        ),
    ]
